name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: zyadwaelmo
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#7c3aed&color_dots=#bfd6f6,#8cc8ff,#64b3f4,#42a5f5,#2196f3
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#7c3aed&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
          
      - name: Show build status
        run: git status
        
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
